// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsQSHl9HSB4qfod6f2lDMLidzBUmdhhBk',
    appId: '1:16650954928:web:1029c4d33f7be686fc3375',
    messagingSenderId: '16650954928',
    projectId: 'c2-firebase-bc087',
    authDomain: 'c2-firebase-bc087.firebaseapp.com',
    databaseURL: 'https://c2-firebase-bc087-default-rtdb.firebaseio.com',
    storageBucket: 'c2-firebase-bc087.appspot.com',
    measurementId: 'G-2TPFHK0H8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_a7Nr8GqNtix-jPoxMG2sEfM77vVdoTE',
    appId: '1:16650954928:android:85ad2b352d1d1874fc3375',
    messagingSenderId: '16650954928',
    projectId: 'c2-firebase-bc087',
    databaseURL: 'https://c2-firebase-bc087-default-rtdb.firebaseio.com',
    storageBucket: 'c2-firebase-bc087.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0406_rftzgH3PaMuw_najy619EnxdbrY',
    appId: '1:16650954928:ios:9bcde16b48d2d70ffc3375',
    messagingSenderId: '16650954928',
    projectId: 'c2-firebase-bc087',
    databaseURL: 'https://c2-firebase-bc087-default-rtdb.firebaseio.com',
    storageBucket: 'c2-firebase-bc087.appspot.com',
    iosBundleId: 'com.example.flutterprojects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0406_rftzgH3PaMuw_najy619EnxdbrY',
    appId: '1:16650954928:ios:9bcde16b48d2d70ffc3375',
    messagingSenderId: '16650954928',
    projectId: 'c2-firebase-bc087',
    databaseURL: 'https://c2-firebase-bc087-default-rtdb.firebaseio.com',
    storageBucket: 'c2-firebase-bc087.appspot.com',
    iosBundleId: 'com.example.flutterprojects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsQSHl9HSB4qfod6f2lDMLidzBUmdhhBk',
    appId: '1:16650954928:web:0a33c4fc5401ceccfc3375',
    messagingSenderId: '16650954928',
    projectId: 'c2-firebase-bc087',
    authDomain: 'c2-firebase-bc087.firebaseapp.com',
    databaseURL: 'https://c2-firebase-bc087-default-rtdb.firebaseio.com',
    storageBucket: 'c2-firebase-bc087.appspot.com',
    measurementId: 'G-S1XQ1LMY8E',
  );

}